### ISSUE TITLE
inconsistent XML output: attribute "value" is used instead of "varname" in <frame>

### ISSUE THREAD

**Issue by timmli** [spetitjean/XMG-2#11]
This is the output of feature structures in `<syn>`:

    <fs coref="@J">
      <f name="agr">
        <sym varname="@A"/>
      </f>
    </fs>

However, the output of feature structures in `<frame>` uses `value` instead of `varname` 

    <fs coref="@Frame3" type="[activity,event]">
      <f name="actor">
        <sym value="@V2"/>
       </f>
    </fs>

Would it be possible to make this more consistent, i.e., replace `value` by `varname` in the latter?

**Comment by spetitjean** [comment]
I think that this was fixed in one of the last commits. Is your version up to date?

**Comment by timmli** [comment]
You mean commit 12dc4ab?

I guess not. How can I see which version I'm using?

**Comment by spetitjean** [comment]
I just updated the version on the server, you can have another try. The install should be changed so that it uses the git repository, but it should work. I'll take care of the migration to git soon.

**Comment by timmli** [comment]
Thanks!

**Comment by timmli** [comment]
There are still some inconsistencies:

    <f name="goal">
      <sym varname="@V6"/>
     </f>
     <f name="mover">
       <sym value="@V4"/>
     </f>
     <f name="path">
       <sym varname="@V7"/>
     </f>

**Comment by spetitjean** [comment]
I don't know how to recreate the bug but it could be fixed now.
