### ISSUE TITLE
allow for dropping types in frame descriptions

### ISSUE THREAD

**Issue by timmli** [spetitjean/XMG-2#12]
Currently, it's not possible to describe a frame without explicitly referring to the type, either with a type name or a type variable. I think it would be good to be able to drop them and just specify features like this:

    <frame> {
      [feature: value]
    }

**Comment by spetitjean** [comment]
It should be fixed now (the version on the server is up to date too).

**Comment by timmli** [comment]
By the way: It is not permitted to have a feature with name "feature".

**Comment by spetitjean** [comment]
Yes, as "feature" is a keyword, it cannot be used as an identifier. For the same reason, a node cannot be named "node", or "class".
