### ISSUE TITLE
add file import

### ISSUE THREAD

**Issue by timmli** [spetitjean/XMG-2#9]
I think it would be useful to be able to import files containing , e.g., common declarations or other parts of a metagrammar. This would make things easier when getting started or when one wants to factorize large metagrammars.

**Comment by spetitjean** [comment]
I don't know how one could do this with the WebGUI. On a standard installation, that would be using the "include" statement, right?

**Comment by timmli** [comment]
I'm not talking about the WebGUI. How would it be expressed just with plain XMG code? I don't know the include statement...

**Comment by spetitjean** [comment]
Ah, ok. It is:

include file.mg

Typically, all the includes are done in the same file, which contains only the valuations. Having one file for all the type/feature/mutex declarations is quite common. The rest of the files are for the syntactic/semantic fragment descriptions.

**Comment by timmli** [comment]
That's what I wanted, thanks! Maybe `include` should be mentioned in the documentiation (http://dokufarm.phil.hhu.de/xmg/doku.php?id=start)

**Comment by spetitjean** [comment]
True, I thought it was part of the documentation actually (as it was a feature of XMG1).
